### ISSUE TITLE
Release v0.3.0

### ISSUE THREAD

**Issue by at-wat** [T-frog/tf-2md3-firmware#26]
### bug fixes
- [x] Fix absolute angle compensation #18
- [x] Fix INTERRUPT packet forwarding #56
- [x] Re-organize mainloop and interrupt operations #49
- [x] Initialize torque_offset #57
- [x] Fix torque_offset handling #54
- [x] Ignore single-shot hall signal error #59
- [x] Fix stored parameter version update #55
- [x] Fix initial low voltage error #52
- [x] Fix SET_CSR timeout handling #43
- [x] Fix embedded binary parameter loading #40
- [x] Fix isochronous data forwarding #41

### new features
- [x] Add encoder denominator parameter #19
- [x] Output error status #21
- [x] Detect inconsistency between encoder and hall signal #25
- [x] Support inverted hall sensor signal #14

**Comment by at-wat** [comment]
Testing for the configurations without encoder denomination.

**Comment by at-wat** [comment]
No problem found on several weeks of long-term operation test.
I will make 0.3.0 release tag soon.

**Comment by at-wat** [comment]
Release is published https://github.com/T-frog/tf-2md3-firmware/releases/tag/v0.3.0

**Comment by at-wat** [comment]
firmware is deployed. closing.
